services:
  service:
    image: registry.sciol.ac.cn/sciol/xyzen-service:latest
    env_file:
      - .env.dev
    build:
      context: ../service
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    volumes:
      - ../service:/app
      - /app/.venv
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "uv sync && uv run python -m app.main"

  celery:
    env_file:
      - .env.dev
    volumes:
      - ../service:/app
      - /app/.venv
    command: sh -c "uv sync && uv run celery -A app.worker worker --loglevel=info"

  web:
    image: registry.sciol.ac.cn/sciol/xyzen-web:latest
    env_file:
      - .env.dev
    build:
      context: ../web
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.yarn
    command: sh -c "corepack enable && yarn install && yarn dev"
